### ISSUE TITLE
Фильтр на копирайт и ссылку на разрабов

### ISSUE THREAD

**Issue by artikus11** [wppuzzle/basic#16]
Приветствую! Предлагаю добавить фильтр на футерные ссылки в теме. На копирайт и ссылку на разработчиков. Все равно их убирают методом жесткого вырезания из кода файла, а так можно будет изящно отфильтровать

**Comment by ghost** [comment]
добавлен фильтр в версии 1.3.3
https://github.com/wppuzzle/basic/releases/tag/1.3.3
