### ISSUE TITLE
Basic Theme – video thumbnail not responsive

### ISSUE THREAD

**Issue by Raghav-TX** [wppuzzle/basic#22]
Thumbnails for videos (e.g. you tube videos added via embed code) are not responsive. Do not appear properly on mobile device.

An example : http://automationstepbystep.com/2017/10/27/jmeter-beginner-tutorial-1-how-to-install-jmeter/

**Comment by ghost** [comment]
fixed at 1.3.4 https://github.com/wppuzzle/basic/commit/5dce6d07e271f65f7b4e194b2b30a25c7ae83c31
