### ISSUE TITLE
Проблемы с меню после обновления!

### ISSUE THREAD

**Issue by YuliaYushchenko** [wppuzzle/basic#23]
После обновления темы до **версии 1.3.5**, возникли проблемы с меню на страницах пагинации. На остальных страницах все работает нормально.
Пример с другого сайта (дефолтные настройки темы): http://i.piccy.info/i9/90a1322bf5ef15ebd9569df97544821f/1512936926/142179/1203989/2017_12_10_224927.jpg
Вот так выглядит главная страница (там все нормально): http://i.piccy.info/i9/650bd838925fb2cda4b1709334833a3c/1512937033/70582/1203989/2017_12_10_224955.jpg

**Comment by YuliaYushchenko** [comment]
также есть проблема с названием кнопки **МЕНЮ** на мобильных
http://prntscr.com/hlw1z7

**Comment by ghost** [comment]
исправлено в 1.3.6
